spring:
  application:
    name: eureka-client-service-mail
  mail:
    host: smtp.126.com
    username: renli0404@126.com
    password: r0227l # authorized code
    properties:
      mail.smtp.auth: true
      mail.smtp.port: 994
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
    default-encoding: UTF-8
  zipkin:
    base-url: http://127.0.0.1:9002/
  sleuth:
    sample:
      probability: 1.0

server:
  port: 7006
  servlet:
    context-path: /mail

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/